# Generated by Django 4.2 on 2024-02-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(default="user.jpg", upload_to="image"),
        ),
    ]
