# Generated by Django 4.2 on 2024-01-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='My Bio', max_length=400),
        ),
    ]
