# Generated by Django 4.2 on 2024-02-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0002_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(default=None, upload_to="image"),
        ),
    ]
