# Generated by Django 4.2 on 2024-01-31 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_subscribers_delete_register'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name_plural': 'Subscribers'},
        ),
    ]
