# Generated by Django 4.2 on 2024-03-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorder",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("shipped", "Shipped"),
                    ("completed", "Completed"),
                    ("delivered", "Delivered"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("disabled", "Disabled"),
                    ("in_review", "In Review"),
                    ("published", "Published"),
                ],
                max_length=50,
            ),
        ),
    ]
