# Generated by Django 4.2 on 2024-01-26 09:44

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=1234567890, max_length=128, region=None, unique=True),
        ),
    ]
