# Generated by Django 4.2 on 2024-01-31 12:37

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='vid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghij12345', length=22, max_length=31, prefix='supplier', unique=True),
        ),
    ]
