# Generated by Django 4.2 on 2024-02-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_product_tags_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='life',
            field=models.CharField(default='10', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='mfd',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_available',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
