# Generated by Django 4.2 on 2024-02-02 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_life_product_mfd_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
