# Generated by Django 4.2 on 2024-02-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_product_description_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
