# Generated by Django 4.2 on 2024-02-07 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_cartorderitems_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='product_status',
            new_name='order_status',
        ),
    ]
