# Generated by Django 4.2 on 2024-02-16 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_cartorder_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name_plural': 'Product Images'},
        ),
    ]
