# Generated by Django 4.2 on 2024-02-16 12:00

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_productimages_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='Nairobi', max_length=30),
        ),
        migrations.AddField(
            model_name='address',
            name='first_name',
            field=models.CharField(default='Jane', max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(default='Doe', max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+2549567890', max_length=128, region=None, unique=True),
        ),
    ]
