# Generated by Django 4.2 on 2024-02-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_address_city_address_first_name_address_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='Kenya', max_length=30),
        ),
        migrations.AddField(
            model_name='address',
            name='county',
            field=models.CharField(default='Nairobi', max_length=30),
        ),
    ]
