# Generated by Django 4.2 on 2024-02-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_shippingcompany'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingcompany',
            options={'verbose_name_plural': 'Shipping Companies'},
        ),
    ]
