# Generated by Django 4.2 on 2024-02-16 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_alter_shippingcompany_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingcompany',
            name='added_by',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Added by'),
        ),
        migrations.AddField(
            model_name='shippingcompany',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingcompany',
            name='company_name',
            field=models.CharField(default='SpeedAF', max_length=50),
        ),
    ]
