# Generated by Django 4.2 on 2024-02-16 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0021_shippingcompany_added_by_shippingcompany_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingcompany',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Added by'),
        ),
    ]
