# Generated by Django 4.2 on 2024-02-19 09:38

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_shippingcompany_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+2549567890', max_length=128, region=None),
        ),
    ]
