# Generated by Django 4.2 on 2024-02-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_address_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingcompany',
            name='company_name',
            field=models.CharField(max_length=50),
        ),
    ]
