# Generated by Django 4.2 on 2024-02-21 08:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_shippingcompany_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='jane doe', max_length=20)),
                ('subject', models.CharField(max_length=60)),
                ('email', models.EmailField(default='janedoe@gmail.com', max_length=254)),
                ('message', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
    ]
