# Generated by Django 4.2 on 2024-02-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
    ]
